### ISSUE TITLE
No module named startup

### ISSUE THREAD

**Issue by mooru** [eliranwong/UniqueBible#1304]
I started getting this error after trying to update the bible app. Not sure what to do 

`Traceback (most recent call last):`
 ` File "/Users/mac/UniqueBible/main.py", line 141, in <module>`
    `from startup.guiQt import *`
`ModuleNotFoundError: No module named 'startup'`

**Comment by onegladiator4u** [comment]
i got the error too like this 
![image](https://user-images.githubusercontent.com/48617390/216755477-c92e7564-002d-4050-95e3-02d52df1648d.png)
![image](https://user-images.githubusercontent.com/48617390/216755525-2e47e4e6-113c-4d00-91d4-5d675b25cf83.png)
![image](https://user-images.githubusercontent.com/48617390/216755554-377178b1-5dc5-4855-b4d1-f558f6cb6d91.png)

i think it's because of no folder named startup

**Comment by mooru** [comment]
adding a folder named startup doesn't seem to solve it

**Comment by onegladiator4u** [comment]
If app not loading you may need to download the three files from it to work i guess. That worked for me.

here https://github.com/eliranwong/UniqueBible/tree/main/startup

**Comment by onegladiator4u** [comment]
Downloading by right clicking and save link file will not work. You may have to copy code and save it as corresponding filename. I don't know how to download . Couldn't see option for that

**Comment by mooru** [comment]
Thanks a bunch. That solved it

**Comment by onegladiator4u** [comment]
Anytime brother. May be you should keep this issue open since the issue is not solved through update .

**Comment by eliranwong** [comment]
I updated the patch file, it should be now fixed.  Thanks for reports and help about this issue.
