### ISSUE TITLE
I cann’t use Unique Bible after updating to Big Sur

### ISSUE THREAD

**Issue by fillgun** [eliranwong/UniqueBible#141]
Hi~ Can i ask something..
i cann’t open U.B on Macbook. I cann’t use Unique Bible after updating to Big Sur.

<img width="1440" alt="스크린샷 2021-02-17 오전 12 19 09" src="https://user-images.githubusercontent.com/7662970/108083043-067ac500-70b6-11eb-82e3-ad261b5b8505.png">

**Comment by eliranwong** [comment]
@otseng can you help @fillgun as you use UBA on Big Sur.  thanks.

**Comment by otseng** [comment]
Can you try renaming config.py to config.1.py and restarting?

**Comment by eliranwong** [comment]
please also can you make sure you have the latest version 21.33?  Thanks.

Major changes in version 21.33:
Substantial update: a total of 32 files changes:

now support dynamic change of menu layout without restart
now support dynamic change of keyboard shortcut set without restart
added ability to edit cutom shortcuts with double-clicking on display shortcut window
added a new tab 'Miscellenous' to 'Master Control' panel
added highlights feature to Master Control
added YouTube downloader buttons to Master Control
added text-to-speech feature to Master Control
fixed keyboard shortcuts to switch between tabs of Master Control
refresh history records when Master Control tab is opened
set the search field in focus when Master Control Search tab is opened
renamed 'Remote Control' to 'mini Control'
increase the number of verse highlight collections from two to twelve
added quick access to verse highlight feature via Master Control
added ability to customise verse highlight collection name and colours
added ability to customise verse number single-click action (via Focus menu layout)
added ability to customise verse number double-click action (via Focus menu layout)
added ability to customise default text-to-speech voice (via Focus menu layout)
improved start-up speed
fixed known startup issues
revised shortcut set 'micron'

**Comment by fillgun** [comment]
I already renaming config.py to config.1.py  and  update 21.35 not working  T.T


<img width="1154" alt="스크린샷 2021-02-18 오전 1 54 03" src="https://user-images.githubusercontent.com/7662970/108241042-c3405500-718e-11eb-9f44-f5daa2a80dd8.png">

**Comment by otseng** [comment]
I just noticed you are using Korean language.  That is probably causing issues.  Will need to figure out how to use Korean on my Mac to duplicate your error.

**Comment by eliranwong** [comment]
@fillgun do you use custom interface translation?  Korean translation?  if so, your translation file may not contain all new elements we substantially added recently.  If this is the case, please switch to default English program interface and try to restart again.  Thanks for trying.

**Comment by fillgun** [comment]
I used english interface .. ㅠ.ㅠ

**Comment by otseng** [comment]
Can you print out debug info and share to help debug the issue?

Instructions:
https://github.com/eliranwong/UniqueBible/wiki/Printing-debug-info

**Comment by fillgun** [comment]
this is my debug screen shot

<img width="870" alt="스크린샷 2021-02-24 오전 11 32 42" src="https://user-images.githubusercontent.com/7662970/108938984-59dfab00-7694-11eb-9f03-2f833c1346f3.png">

**Comment by otseng** [comment]
It's missing the config values so it's not able to run correctly.  Try to run "python main.py", it should recreate the config.py file.  Exit it, then run "python debug.py" again and see if there are values in the config.  If it still does not have config values, we'll need to debug further.

**Comment by fillgun** [comment]
<img width="727" alt="스크린샷 2021-02-24 오후 3 06 35" src="https://user-images.githubusercontent.com/7662970/108955657-e6e52d00-76b1-11eb-8bf7-0db9bed1cf13.png">

**Comment by otseng** [comment]
> When I cleared the config.py file and ran it, the config.py was recreated.
> But it was an empty file.

This shouldn't happen.  Can we do a Skype session and you can share your screen with me to diagnose the issue?

**Comment by eliranwong** [comment]
> When I cleared the config.py file and ran it, the config.py was recreated.
> But it was an empty file.
> 
> So I attached the config.py copied from the file I was using before.
> 
> It still doesn't work. As shown in the first picture, the download helper window nothing happens.
> 
> <img alt="스크린샷 2021-02-24 오후 3 06 35" width="727" src="https://user-images.githubusercontent.com/7662970/108955657-e6e52d00-76b1-11eb-8bf7-0db9bed1cf13.png">

@fillgun Hello Joshua,

a few notes here:

* when you remove config.py, please make sure the app is not running.
* you mentioned the download helper does nothing.  It appears to me that it is the same issue as https://github.com/eliranwong/UniqueBible/issues/183 , which is just in version 21.63.

I leave to @otseng to help you further as he uses big sir

**Comment by otseng** [comment]
Eliran has most likely fixed this with the latest version - 21.68.

**Comment by eliranwong** [comment]
I just tried a run on Big Sir.  It is opened the first time after a fresh installation.  The 2nd time I opened it, the app hangs like Joshua screenshot.

**Comment by eliranwong** [comment]
@fillgun Hello Joshua, I hope it is not too late for you.

I think experienced the same issue as yours when I tried to install on Big Sir yesterday.

but finally found an issue of Python on macOS Big Sur with Xcode (https://github.com/pyenv/pyenv/issues/1643#issuecomment-684050015), it is not an issue about UBA, but I shared a bit how I overcome the issue.

Below is what I did to get UBA running on Big Sur:

(I may write a wiki page about it)

Run the following steps with macOS terminal app.<br>
(please note that some steps below may be optional, but it works on my side.)

1) Install Xcode Command Line Tools

> xcode-select --install

2) Install home-brew (https://brew.sh)

> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

2) Install the python build dependencies and a few other elements (https://github.com/pyenv/pyenv/wiki#suggested-build-environment):

> brew install openssl readline sqlite3 xz zlib bzip2 git

3) Add bzip2 path

(One may use the following line to check which shell is being used. recent macOS versions use zsh by default, older versions use bash by default):

> echo $SHELL

(For bash users)<br>
> echo 'export PATH="/usr/local/opt/bzip2/bin:$PATH"' >> ~/.bash_profile<br>
> echo 'export LDFLAGS="-L/usr/local/opt/bzip2/lib"' >> ~/.bash_profile<br>
> echo 'export CPPFLAGS="-I/usr/local/opt/bzip2/include" >> ~/.bash_profile<br>

(For zsh users)<br>
> echo 'export PATH="/usr/local/opt/bzip2/bin:$PATH"' >> ~/.zshrc<br>
> echo 'export LDFLAGS="-L/usr/local/opt/bzip2/lib"' >> ~/.zshrc<br>
> echo 'export CPPFLAGS="-I/usr/local/opt/bzip2/include" >> ~/.zshrc<br>

4) Install pyenv (https://github.com/pyenv/pyenv):

> brew install pyenv

5) Add pyenv path

(for bash user, run)<br>
> echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile

or 

(for zsh user, run)<br>
> echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc

6) Restart terminal app (or you may simply open a new tab)

7) Install python 3.7.3 (you may choose other version from version 3.7 or above; read more at: https://github.com/pyenv/pyenv/issues/1643#issuecomment-684050015)

CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(xcrun --show-sdk-path)/usr/lib" \
pyenv install --patch 3.8.3 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch)

8) Set pyenv global to 3.7.3 (you may want to set a particular python version only for UBA, rather than global.  read more at: https://github.com/pyenv/pyenv):

> pyenv global 3.7.3

8) Download UBA with git

> git clone https://github.com/eliranwong/UniqueBible

9) Run UBA:

> python3 UniqueBible/uba.py

DONE! finally ...

**Comment by eliranwong** [comment]
it is not an issue about UBA.  it is an issue about macOS / Xcode. @fillgun if you do not have further question about installing UBA on Big Sur, we will close this issue a few days later.

**Comment by eliranwong** [comment]
please also note that we recently change the way how UBA is installed:

https://github.com/eliranwong/UniqueBible/wiki/Install-on-macOS

**Comment by fillgun** [comment]
I done~~ ^^ thank you so much

but I try to install on Mac M1 cpu ^^
