### ISSUE TITLE
After update UBA not opening

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#146]
Hi brother,
This time after update I got errors from file gui/mainwindow.py I replaced it from cloning this repository using GitHub desktop.
But this error shows up
![image](https://user-images.githubusercontent.com/48617390/108169774-2b575280-711f-11eb-9dc9-af8378fa1ed5.png)

**Comment by eliranwong** [comment]
@onegladiator4u it seems this is an issue already fixed in one of earlier versions, I think.

can you try to have a fresh install of version 21.33, which I just uploaded, and try again?

Major changes in version 21.33:
Substantial update: a total of 32 files changes:
* now support dynamic change of menu layout without restart
* now support dynamic change of keyboard shortcut set without restart
* added ability to edit cutom shortcuts with double-clicking on display shortcut window
* added a new tab 'Miscellenous' to 'Master Control' panel
* added highlights feature to Master Control
* added YouTube downloader buttons to Master Control
* added text-to-speech feature to Master Control
* fixed keyboard shortcuts to switch between tabs of Master Control
* refresh history records when Master Control tab is opened
* set the search field in focus when Master Control Search tab is opened
* renamed 'Remote Control' to 'mini Control'
* increase the number of verse highlight collections from two to twelve
* added quick access to verse highlight feature via Master Control
* added ability to customise verse highlight collection name and colours
* added ability to customise verse number single-click action (via Focus menu layout)
* added ability to customise verse number double-click action (via Focus menu layout)
* added ability to customise default text-to-speech voice (via Focus menu layout)
* improved start-up speed
* fixed known startup issues
* revised shortcut set 'micron'

**Comment by onegladiator4u** [comment]
Ok bro.

**Comment by onegladiator4u** [comment]
Brother I just deleted the whole uniquebible folder and freshly installed all. Still this error
![image](https://user-images.githubusercontent.com/48617390/108223448-d851bf80-715f-11eb-8cef-a92f49ecaef7.png)

**Comment by eliranwong** [comment]
@onegladiator4u can you try to open file "MasterControl.py" in UBA folder "gui" with Windows notepad, and remove the following two lines:

>import shortcut as sc<br>
> from util.ShortcutUtil import ShortcutUtil

saved the file, and restart the app?

@otseng can you help take a look into this issue.  is it possible relate to a recent change in shortcut feature?

**Comment by eliranwong** [comment]
I removed these two lines in version 21.35.  in addition, @otseng had a fix in version 21.34.  It may relate to this issue.  please kindly try and let us know.  thanks for your help.

**Comment by onegladiator4u** [comment]
I removed those lines too. Now number of errors decreased. But still not opening.
May I know how to update to latest version?

**Comment by onegladiator4u** [comment]
Replaced the code in main.py. It's working. Thanks

**Comment by onegladiator4u** [comment]
Can I ask one more thing?
Will uba files get corrupt if i close the app and restart it fast?
Or if I don't restart the app after an update until next restart?

**Comment by eliranwong** [comment]
> Can I ask one more thing?
> Will uba files get corrupt if i close the app and restart it fast?
> Or if I don't restart the app after an update until next restart?

Not really, I think.  but I suggest you restart after an upgrade.  When you see the file latest_changes.txt opened with notepad automatically, it means all necessary files are in place "theoretically"

**Comment by eliranwong** [comment]
bty, now you have 12 highlight collections, @onegladiator4u thanks again for suggesting us to add highlight feature.

now you can easily rename collection and change colours.

you may try one thing, configure double-click action via Focus menu layout and select Miscellaneous.  Double-click a verse number allow you to highlight that particular verse.

**Comment by onegladiator4u** [comment]
Thanks for the feature bro. Will definitely try it out.
