### ISSUE TITLE
Update control

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#178]
How about an option to turn off check for update for the app on startup? If someone don't want to update for some time.
And adding an option to check for update in About/information menu. If anyone is annoyed by daily update they can turn off and do a manual update inside when they want.

**Comment by otseng** [comment]
I'll work on this.

**Comment by otseng** [comment]
Here's how I'll design it:

A update configuration window displaying latest version, current version, when next scheduled update, days between updates, and button to update now.

Because we now have support for multiple languages, it'd be best to display the next schedule update in the format for that language.  

```
English: 2/23/21
Chinese:  2021/2/23
German: 23.02.21
```

To do this, I'm going to use the [babel library](http://babel.pocoo.org/en/latest/index.html).  This will require the babel module to be installed.  But, it will lay the groundwork for future support of multiple languages.

**Comment by otseng** [comment]
This is a significant change.  So, there could be issues.  Please create a new issue to report bugs.

**Need to run "pip install babel" with this update.**  Future development will rely on this module for internationalization to support multiple languages.

**Comment by onegladiator4u** [comment]
> This is a significant change. So, there could be issues. Please create a new issue to report bugs.

Ok brother.

**Comment by onegladiator4u** [comment]
@otseng bro can I suggest one thing one thing for this .it's a minor thing. Can you change color of the `it's up to date` in normal theme. It's not readable.
![image](https://user-images.githubusercontent.com/48617390/109155903-2be28f80-7796-11eb-9f9b-cf3bf5a1d0df.png)
Thanks in advance.

**Comment by otseng** [comment]
Will change to blue in next update.
