### ISSUE TITLE
Support custom fonts for non-English Bibles

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#187]
Would like to see my non-English Bibles in a native language font.

**Comment by otseng** [comment]
@onegladiator4u 
What non-English bible are you using?  
Where can I get it?  
What is the name of the font you want to use?

**Comment by onegladiator4u** [comment]
I just uploaded to drive. the language is Malayalam. It's an Indian language.
https://drive.google.com/file/d/1Jl0S0RFObb1w-e-6qjVmuSrB-C4nL4fq/view?usp=sharing
May I know why you need this? I thought this will work for all non English language.

**Comment by otseng** [comment]
Thanks.  I want to make it so when you select this Bible, it will automatically select your language font.

**Comment by onegladiator4u** [comment]
Oh ok. Will that happen to all non English Bible too? This will be difficult right ? Since people prefer different font in their own native language.

**Comment by eliranwong** [comment]
@otseng I prefere not to use a single font for all bibles of a single language if possible.  Because even bible modules have the same languages, they can require different font files.

a read example is that, SBLGNT greek bible requires a specific font in some other softwares.

It would be more flexible if bible module details table can specify a font the module creator would like to display it.

**Comment by otseng** [comment]
Yes, I'll do that instead to make it most flexible.  I'll have a specific font(s) tied to a specific Bible.

**Comment by eliranwong** [comment]
@otseng I think it would be nice if user can specify font for a bible by using the font dialog window, like the one we use to select default font in general, so that users can change font for a bible even they have no knowledge about sqlite file.

my brief idea is described below

* in each bible file, we may consider add an entry "font" in "Details" table
* the font entry is empty by default
* if user doesn't specify a font for the opened bible, general default font will be used for displaying its bible text
* if a user want to specify a font for a bible, they can first open a bible on main window
* then open font dialog to specify a font for the opened bible.
* when they click "ok" button on font dialog box, the app insert the font entry in Details table for users, so they don't need to manually handle the sqlite file.

just a suggestion, what do you think?

**Comment by onegladiator4u** [comment]
Do you guys think 'details' table need only one entry? I thought it'll be needing font size too. 
I want to suggest one more thing that after introducing this feature when Opening a bible version or moving to a different tab the font display portion also gets updated in case you missed.
![image](https://user-images.githubusercontent.com/48617390/109338693-9a097e00-788c-11eb-810a-6052c6513bfb.png)
For example if we opened two Bible versions in tabs
![image](https://user-images.githubusercontent.com/48617390/109339062-143a0280-788d-11eb-8d66-7a0b4b5416a4.png)
If that font display portion don't get updated when switching tabs if we increase or decrease font size using buttons the font might charge.
Just a suggestion.

**Comment by eliranwong** [comment]
> Do you guys think 'details' table need only one entry? I thought it'll be needing font size too.
> I want to suggest one more thing that after introducing this feature when Opening a bible version or moving to a different tab the font display portion also gets updated in case you missed.
> ![image](https://user-images.githubusercontent.com/48617390/109338693-9a097e00-788c-11eb-810a-6052c6513bfb.png)
> For example if we opened two Bible versions in tabs
> ![image](https://user-images.githubusercontent.com/48617390/109339062-143a0280-788d-11eb-8d66-7a0b4b5416a4.png)
> If that font display portion don't get updated when switching tabs if we increase or decrease font size using buttons the font might charge.
> Just a suggestion.

I think it would be nice to also have font size entry for each bible.

but regarding the button, I suggest not to change the button display, as many tabs could be opened on many different kinds of resources or features (on a tab show compare or parallel versions, different fonts could be used on the same tab if different versions are compared).  changing display of this button can cause confusion.  I would like to have this button dedicated to the default font and size.

**Comment by onegladiator4u** [comment]
Oh ok. Understood the problem.

**Comment by eliranwong** [comment]
I think custom font would be a very useful feature.  Long time ago, a Russian brother already asked me for custom font on individual commentaries.  Thanks for bringing up this issue.

**Comment by otseng** [comment]
Ok, so the details table in the bible file would contain the font name and font size.  

I'll create a way to configure this for an individual bible.  Then use this info during the display of the bible.

**Comment by otseng** [comment]
Significant changes with this one, so there could be issues.  Please create a new issue to report it.

To use, select "Modify Database" in menu.  This has been added to all menus.

Select the Bible database file, enter font size and select font name.  Try "x-small" or "x-large" for font size.  

Now, when reading a Bible, it will apply that style only to that Bible.

This only works when reading a single Bible.  It does not work when comparing verses with different Bibles.

**Comment by onegladiator4u** [comment]
@otseng Can we expect a future update where it works on comparing verses with different Bible's too?

**Comment by otseng** [comment]
> @otseng Can we expect a future update where it works on comparing verses with different Bible's too?

Yes, that can be added at a later date.

**Comment by onegladiator4u** [comment]
@otseng thanks for the update.
