### ISSUE TITLE
Dark mode, themes?

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#21]
Can you add option for dark mode?  Or even better, add themes?

**Comment by eliranwong** [comment]
Hello Oliver,  Merry Christmas to you.

I think your suggestion is very good.  There may be 3 possibilities with which we can see this happen:

1) Currently, I am working a new project to integrate Desktop and mobile version into a single application, bringing improvement, resources, a unified interface ...  You may find the project at https://github.com/eliranwong/UniqueBibleAppExpanded  This project will have options to change theme colours.

2) After the project I mentioned above grows mature, I may come back to this one and see how themes may be added.  but no guarantee, because I am not very good in programming.

3) I welcome you or others to contribute your codes on theme changing or other additional features.  After you finish, you can post a pull request and I will merge that.

Thanks once again for your message.

**Comment by otseng** [comment]
Merry Christmas.   Thanks for the quick response.

I'll fork the code and play around with it and see if I can add a dark mode.

**Comment by eliranwong** [comment]
Great!  thanks for your contribution to coding.  looking forward to your good news.

**Comment by otseng** [comment]
I've created a pull request for adding dark theme:

https://github.com/eliranwong/UniqueBible/pull/23

**Comment by eliranwong** [comment]
Thank you very much, Oliver.  I am grateful to your contribution.  I have merged your pull request.  I will increase the version number later today to notify users about the upgrade.  Thanks once again.

**Comment by eliranwong** [comment]
Oliver, I think I need your help.  After merging your files, the font settings go wrong.  all fonts on my side become very small.  Even I change the font settings, the app doesn't update the font size.  Is there something break with the new codes?

**Comment by otseng** [comment]
Can we chat on Skype?  My username is otseng.

**Comment by otseng** [comment]
I think I figured it out.  

PR:  https://github.com/eliranwong/UniqueBible/pull/24

**Comment by eliranwong** [comment]
Hello Otseng,  sorry, missed your message here.  I just uploaded a fix.  I will look at your pull request too.  Many thanks.

**Comment by eliranwong** [comment]
Hello, I took a look at your latest pull request.  Thanks for time sorting it out.  I found that I did the same fix as your pull request in my last few commit.  Therefore, I didn't merge your lastest pull request.  The issue was fixed.  Thanks once again for making the app better.  I really appreciate your contribution.  I am not an IT person.  I may need more help from you in the future.  Thanks once again.
