### ISSUE TITLE
Book on new window

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#226]
When I elect to have a book opened on a new window, is there a way I can change the default size of that window? Or can I save the new size settings of that window when I enlarge it?

**Comment by otseng** [comment]
I assume you mean opening a book in the study window.  I can add support of that through macros.

**Comment by darrelwright** [comment]
No I am talking about opening a book in a separate window

**Comment by otseng** [comment]
Got it.  I'll add that ability to set the size of the new window.

**Comment by eliranwong** [comment]
I am not sure if it is relevant to the issue here.

from version 22.17, you can select "New Window" from right-click context menu to display Main / Study Window content on New Window.  Font settings applied to the original content applies to New Window too.  That means you can change the general default font size and it will be applied to New Window too.  may be you want else ...

**Comment by darrelwright** [comment]
I understand regarding the font size. I am hoping to be able to make the window a different size and then be able to keep those new settings.

**Comment by eliranwong** [comment]
you can use different sizes in current setup by turning off the flag "overwriteBookFontSize".

If size change on a particular.  I'm afraid it may cause confusion.

I think a better solution is something like individual bible font settings.  I may be different font setting applied to individual books rather than on the separate window.

reason: that window is not dedicated only for book, that window loads other resources as well.

if a different font applied to that window.  ...  I think there may be issues.

**Comment by eliranwong** [comment]
@otseng 

we want to support book displaying in different font sizes, I think we better focus on book content not on the window @darrelwright mentioned.

I suggest two possible solution:

1) add support of default font size on all book modules.  To achieve it, we need only a change of few words in current codes, I think.

2) add support of different font size on individual books, like current bible settings.  It takes more work.

**Comment by otseng** [comment]
Added config values to set size of the popover window:
popoverWindowWidth
popoverWindowHeight

**Comment by eliranwong** [comment]
this issue was closed automatically with merging https://github.com/eliranwong/UniqueBible/pull/236.  now reopen.

**Comment by otseng** [comment]
Added overwriteBookFontFamily to config.  

Also modified how overwriteBookFontSize works.  It now supports boolean, int, and string.  If True, it'll use the UBA font size.  If int, it'll set it in px size.  If string, it'll use the string.

Examples:

overwriteBookFont = False
overwriteBookFontFamily = ''
overwriteBookFontSize = False

overwriteBookFont = True
overwriteBookFontFamily = 'Minstral'
overwriteBookFontSize = 20  

overwriteBookFont = True
overwriteBookFontFamily = ''
overwriteBookFontSize = 'xx-large'

**Comment by darrelwright** [comment]
Thank you! I appreciate the features that are being added.

**Comment by darrelwright** [comment]
Not sure if this should be added on this issue. When I have a book open in a new book window and I click on a scripture in that book, the scripture opens in the Bible just as it should. But the book jumps back to the beginning of the book rather than staying at its current location. It should not move to the beginning of the book.
