### ISSUE TITLE
Searching lexicon for all topics

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#649]
I have a lexicon with a whole lot of topics. How can I search and display all topics in the study window? I I want to use a wild card to return all entries in the lexicon. Here is a copy of the lexicon I am working with.

[Dake-topics.lexicon.zip](https://github.com/eliranwong/UniqueBible/files/6797721/Dake-topics.lexicon.zip)
Once I have them displayed then I can do another search for a specific data entry in that lexicon.

**Comment by otseng** [comment]
There's no way I can see to do this right now.  This will have to be added.

**Comment by darrelwright** [comment]
So there is no wildcard that can be applied to lexicon searches as there 
is with books?

**Comment by otseng** [comment]
I'm planning on adding support for:
`SEARCHLEXICON:::Dake-topics:::Jesus`
It will then return a list of all topics with Jesus in the lexicon.  Then you click on a topic to see the definition.
The minicontrol will change to use "SEARCHLEXICON:::" instead of "LEXICON:::"

**Comment by darrelwright** [comment]
If you could also allow all topics to be returned. Dakes has a 
commentary and dictionary (which I have both working in UBA), where you 
pull the commentary for the verse you're currently on. Then you select 
an entry that takes you to the dictionary. Now this is the tough part. 
In BA you have a drop-down list showing all entries for further search, 
and that is the list I want to go after with my request.

**Comment by otseng** [comment]
In the miniControl and in the context menu, the lexicon now does a SEARCHLEXICON::: instead of a LEXICON:::
This will return a search of the list of topics.  Then you click on a topic to see the definition.  

What I like about the SEARCHLEXICON over the LEXICON is you can highlight any word, Strongs number, etc and it will return a result.  With LEXICON, it must match exactly the topic entry.

In the context menu, you can also search for ALL lexicons.  This can produce a lot of results.  You can go through them all to view the definitions by opening in context menu "Open Content in", "New Window".  Then when you click on a topic in the new window, it will display the definition in the study window.

In the masterControl, it still does a LEXICON search.

**Comment by darrelwright** [comment]
Oliver, the searchlexicon is superb! It does what I was doing with the 
work-around book where I can enter "SEARCHLEXICON:::Dake-topics:::" and 
pull up all the dictionary entries or enter 
"SEARCHLEXICON:::Dake-topics:::390" and pull all entries containing 390. 
Thanks so much!
