### ISSUE TITLE
"Plain" Bibles not working after upgrade to 20.4

### ISSUE THREAD

**Issue by Difflugia** [eliranwong/UniqueBible#70]
I just upgraded from 18.5 to 20.4 on Ubuntu Linux 18.04.

After the upgrade and on the first restart, I see duplicate links for LXX, OHGB, and OHGBi, but everything otherwise works as expected.

After the second restart, I get the "Some of your files are old. We are helping you to upgrade..." dialog.

After that and subsequent restarts, I see duplicate links, but clicking on them doesn't give me book names. Other Bibles work as expected.

The marvelData/bibles directory now has files for each of the three nonworking Bibles that weren't there before. I assume this is expected and that's what the dialog was telling me was being done. If I change the function "getPlainBibleList" at lines 46-47 of BiblesSqlite.py, I can restore functionality.

Original:
`    def getPlainBibleList(self):
        return ["OHGB", "OHGBi", "LXX"]`

Update:
`    def getPlainBibleList(self):
        return [ ]`

After that, I see one link for each Bible and they work as expected.

**Comment by eliranwong** [comment]
@Difflugia thanks for reporting the issue

@otseng can you take a look into this issue when you have time.  You mentioned yesterday that OHGB is migrated automatically and the file went wrong.  I think that may relate to the same issue report here.  Is it possible that it is caused by one of recent commits which involves codes on migration due to adding "Details" table to bible modules?

**Comment by otseng** [comment]
Yes, I'll fix it in my next PR.
